import logging

import requests

logger = logging.getLogger(__name__)

# ClickUp priority: 1=urgent, 2=high, 3=normal, 4=low
_PRIORITY_MAP = {
    "Urgent": 1,
    "High": 2,
    "Medium": 3,
    "Low": 4,
}

_BASE_URL = "https://api.clickup.com/api/v2"


class ClickUpClient:
    def __init__(self, api_token: str, list_id: str, assignee_id: str):
        self.headers = {
            "Authorization": api_token,
            "Content-Type": "application/json",
        }
        self.list_id = list_id
        self.assignee_id = assignee_id

    def create_task(self, analysis: dict, issue: dict) -> dict | None:
        priority = _PRIORITY_MAP.get(analysis.get("severity", "Medium"), 3)
        description = self._build_description(analysis, issue)

        payload = {
            "name": analysis["title"],
            "description": description,
            "priority": priority,
            "assignees": [int(self.assignee_id)],
            "tags": [
                "google-ads",
                "automated-monitor",
                issue.get("type", "unknown").replace("_", "-"),
                analysis.get("severity", "medium").lower(),
            ],
            "status": "to do",
        }

        try:
            resp = requests.post(
                f"{_BASE_URL}/list/{self.list_id}/task",
                headers=self.headers,
                json=payload,
                timeout=30,
            )
            resp.raise_for_status()
            task = resp.json()
            logger.info(f"ClickUp task created: {task['id']} — {task['name']}")
            return task
        except requests.HTTPError as e:
            logger.error(
                f"ClickUp HTTP error {e.response.status_code}: {e.response.text}"
            )
        except requests.RequestException as e:
            logger.error(f"ClickUp request failed: {e}")
        return None

    def _build_description(self, analysis: dict, issue: dict) -> str:
        actions_md = "\n".join(
            f"- {a}" for a in analysis.get("recommended_actions", [])
        )
        return (
            f"## Issue Detected\n{analysis.get('description', '')}\n\n"
            f"## Business Impact\n{analysis.get('business_impact', '')}\n\n"
            f"## Recommended Actions\n{actions_md}\n\n"
            f"## Issue Details\n"
            f"- **Account:** {issue.get('account_name', 'N/A')} "
            f"(`{issue.get('account_id', 'N/A')}`)\n"
            f"- **Issue Type:** {issue.get('type', 'N/A').replace('_', ' ').title()}\n"
            f"- **Severity:** {analysis.get('severity', 'N/A')}\n"
            f"- **Campaign:** {issue.get('campaign_name', 'N/A')}\n"
            f"- **Raw Details:** {issue.get('details', 'N/A')}\n\n"
            f"*Auto-generated by Google Ads Monitor*"
        )
