import logging

import requests

logger = logging.getLogger(__name__)

_BASE_URL = "https://api.clickup.com/api/v2"

# ClickUp priority: 1=urgent, 2=high, 3=normal, 4=low
_PRIORITY_MAP = {"Urgent": 1, "High": 2, "Medium": 3, "Low": 4}


class ClickUpClient:
    def __init__(self, api_token: str, list_id: str, assignee_id: str):
        self.headers = {
            "Authorization": api_token,
            "Content-Type": "application/json",
        }
        self.list_id = list_id
        self.assignee_id = int(assignee_id)

    def create_campaign_review_task(self, result: dict, config: dict) -> dict | None:
        budget_daily = config["campaign"]["budget_micros"] / 1_000_000
        geo_names = config["geo_targeting"].get(
            "location_names", config["geo_targeting"]["location_ids"]
        )
        offers = config.get("unique_offers", [])
        ext = result.get("extensions", {})

        description = (
            f"## New MSP Campaign Ready for Review\n\n"
            f"A new Google Ads campaign has been created in **PAUSED** state. "
            f"Review the settings below, make any final adjustments in the Google Ads UI, "
            f"then enable it.\n\n"
            f"## Campaign Details\n"
            f"- **Client:** {result['client_name']}\n"
            f"- **Customer ID:** {result['customer_id']}\n"
            f"- **Campaign:** {result['campaign_name']}\n"
            f"- **Status:** PAUSED — needs manual enable\n"
            f"- **Daily Budget:** ${budget_daily:.2f}\n"
            f"- **Bidding:** {config['campaign'].get('bidding_strategy', 'maximize_conversions')}\n"
            f"- **Landing Page:** {result['landing_page']}\n"
            f"- **Service Area:** {config.get('service_area', 'N/A')}\n"
            f"- **Geo Targets:** {', '.join(str(g) for g in geo_names)}\n\n"
            f"## Assets Created\n"
            f"- Keywords uploaded: {result.get('keywords_uploaded', 0)}\n"
            f"- Sitelinks: {ext.get('sitelinks', 0)}\n"
            f"- Callouts: {ext.get('callouts', 0)}\n"
            f"- Structured snippets: {ext.get('structured_snippets', 0)}\n"
            f"- Call extension: {'Yes' if ext.get('call') else 'No'}\n\n"
            f"## Client Offers\n"
            + "\n".join(f"- {o}" for o in offers)
            + f"\n\n## Review Checklist\n"
            f"- [ ] Verify landing page is live and converting\n"
            f"- [ ] Confirm call tracking number is active\n"
            f"- [ ] Review keywords and negatives\n"
            f"- [ ] Preview RSA in Google Ads Editor\n"
            f"- [ ] Enable campaign\n\n"
            f"*Auto-generated by Google Ads Campaign Loader*"
        )

        payload = {
            "name": f"{result['client_name']} — Review & Enable: {result['campaign_name']}",
            "description": description,
            "priority": 2,  # High
            "assignees": [self.assignee_id],
            "tags": [
                "google-ads",
                "campaign-loader",
                "needs-review",
            ],
            "status": "to do",
        }

        return self._post_task(payload)

    def create_campaign_review_task_from_summary(
        self,
        campaign_name: str,
        summary_markdown: str,
        client_name: str,
    ) -> dict | None:
        payload = {
            "name": f"{client_name} — Review & Enable: {campaign_name}",
            "description": summary_markdown,
            "priority": 2,
            "assignees": [self.assignee_id],
            "tags": ["google-ads", "campaign-loader", "needs-review"],
            "status": "to do",
        }
        return self._post_task(payload)

    def create_issue_task(
        self,
        title: str,
        description: str,
        priority: str = "Medium",
        tags: list[str] | None = None,
    ) -> dict | None:
        payload = {
            "name": title,
            "description": description,
            "priority": _PRIORITY_MAP.get(priority, 3),
            "assignees": [self.assignee_id],
            "tags": tags or ["google-ads", "daily-check"],
            "status": "to do",
        }
        return self._post_task(payload)

    def _post_task(self, payload: dict) -> dict | None:
        payload["notify_all"] = True
        payload.setdefault("custom_fields", []).append(
            {
                "id": "0f7cacea-10c6-419f-8501-f1e96e51241b",
                "value": "e2c997ea-6188-4f92-9343-6eb8b4b2bf6e",
            }
        )
        try:
            resp = requests.post(
                f"{_BASE_URL}/list/{self.list_id}/task",
                headers=self.headers,
                json=payload,
                timeout=30,
            )
            resp.raise_for_status()
            task = resp.json()
            logger.info(f"ClickUp task created: {task['id']} — {task['name']}")
            return task
        except requests.HTTPError as e:
            logger.error(
                f"ClickUp HTTP error {e.response.status_code}: {e.response.text}"
            )
        except requests.RequestException as e:
            logger.error(f"ClickUp request failed: {e}")
        return None
