import json
import logging
import os
import sys
from pathlib import Path

from dotenv import load_dotenv
from google.ads.googleads.client import GoogleAdsClient

from checks.daily_checker import DailyChecker
from checks.landing_page_checker import check_all_clients
from loader.clickup_client import ClickUpClient
from loader.discord_notifier import DiscordNotifier

load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s — %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
    stream=sys.stdout,
)
logger = logging.getLogger(__name__)

_REQUIRED_ENV = [
    "GOOGLE_ADS_DEVELOPER_TOKEN",
    "GOOGLE_ADS_CLIENT_ID",
    "GOOGLE_ADS_CLIENT_SECRET",
    "GOOGLE_ADS_REFRESH_TOKEN",
    "GOOGLE_ADS_LOGIN_CUSTOMER_ID",
    "CLICKUP_API_TOKEN",
    "CLICKUP_LIST_ID",
    "CLICKUP_ASSIGNEE_ID",
    "DISCORD_WEBHOOK_URL",
]

_HERE = Path(__file__).parent
_CLIENTS_DIR = str(_HERE / "clients")
_REGISTRY_FILE = _HERE / "campaign_registry.json"


def _load_env() -> dict:
    missing = [k for k in _REQUIRED_ENV if not os.environ.get(k)]
    if missing:
        logger.error(f"Missing required environment variables: {', '.join(missing)}")
        sys.exit(1)
    return {k: os.environ[k] for k in _REQUIRED_ENV}


def _load_managed_customer_ids() -> list[str]:
    """
    Returns unique customer IDs from the campaign registry (campaigns we created).
    Falls back to empty list — the monitor handles all-accounts sweeps.
    """
    if not _REGISTRY_FILE.exists():
        return []
    try:
        data = json.loads(_REGISTRY_FILE.read_text(encoding="utf-8"))
        seen = set()
        ids = []
        for campaign in data.get("campaigns", []):
            cid = campaign.get("customer_id", "").replace("-", "")
            if cid and cid not in seen:
                seen.add(cid)
                ids.append(cid)
        return ids
    except Exception as e:
        logger.error(f"Failed to read campaign registry: {e}")
        return []


def main():
    env = _load_env()

    google_client = GoogleAdsClient.load_from_dict({
        "developer_token": env["GOOGLE_ADS_DEVELOPER_TOKEN"],
        "client_id": env["GOOGLE_ADS_CLIENT_ID"],
        "client_secret": env["GOOGLE_ADS_CLIENT_SECRET"],
        "refresh_token": env["GOOGLE_ADS_REFRESH_TOKEN"],
        "login_customer_id": env["GOOGLE_ADS_LOGIN_CUSTOMER_ID"],
        "use_proto_plus": True,
    })

    clickup = ClickUpClient(
        env["CLICKUP_API_TOKEN"], env["CLICKUP_LIST_ID"], env["CLICKUP_ASSIGNEE_ID"]
    )
    discord = DiscordNotifier(env["DISCORD_WEBHOOK_URL"])

    # 1. Google Ads checks (disapprovals, billing, conversion tracking)
    customer_ids = _load_managed_customer_ids()
    checker = DailyChecker(google_client)
    ads_issues = checker.run_all_checks(customer_ids) if customer_ids else []

    # 2. Landing page checks (HTTP status + response time)
    landing_issues = check_all_clients(_CLIENTS_DIR)

    total_issues = len(ads_issues) + len(landing_issues)
    logger.info(
        f"Daily check complete — {len(ads_issues)} ads issue(s), "
        f"{len(landing_issues)} landing page issue(s)"
    )

    # 3. Create ClickUp tasks for actionable issues
    for issue in ads_issues:
        title = (
            f"{issue.get('account_name', issue.get('client_name', 'Unknown'))} — "
            f"{issue['type'].replace('_', ' ').title()}"
        )
        clickup.create_issue_task(
            title=title,
            description=(
                f"## Issue Detected\n{issue['details']}\n\n"
                f"- **Account:** {issue.get('account_name', 'N/A')} "
                f"(`{issue.get('account_id', 'N/A')}`)\n"
                f"- **Campaign:** {issue.get('campaign_name', 'N/A')}\n\n"
                f"*Auto-generated by Google Ads Campaign Loader — Daily Check*"
            ),
            priority="High" if issue["type"] in ("billing_issue", "ad_disapproval") else "Medium",
            tags=["google-ads", "daily-check", issue["type"].replace("_", "-")],
        )

    for issue in landing_issues:
        title = f"{issue['client_name']} — Landing Page {issue['type'].replace('_', ' ').title()}"
        priority = "High" if issue["status_code"] >= 400 or issue["status_code"] == 0 else "Medium"
        clickup.create_issue_task(
            title=title,
            description=(
                f"## Landing Page Issue\n{issue['details']}\n\n"
                f"- **Client:** {issue['client_name']}\n"
                f"- **URL:** {issue['url']}\n"
                f"- **HTTP Status:** {issue['status_code']}\n"
                f"- **Response Time:** {issue['elapsed_s']}s\n\n"
                f"*Auto-generated by Google Ads Campaign Loader — Daily Check*"
            ),
            priority=priority,
            tags=["google-ads", "daily-check", "landing-page"],
        )

    # 4. Discord summary
    discord.daily_check_summary(ads_issues, landing_issues)

    if total_issues:
        logger.warning(f"{total_issues} issue(s) found — ClickUp tasks created.")
    else:
        logger.info("All checks passed.")


if __name__ == "__main__":
    main()
